/srv/travel-agent/logs/mysql/*.log /srv/travel-agent/logs/redis/*.log /srv/travel-agent/logs/migrate/*.log {
    daily
    maxsize 20M
    rotate 14
    missingok
    notifempty
    compress
    delaycompress
    copytruncate
    su root root
}
