"""Deterministic itinerary solver primitives."""

from .anchors import resolve_day_time_bounds
from .availability import assign_attraction_date, assign_to_nearest_available_date, is_open_on
from .data_gate import filter_solver_inputs
from .models import (
    AnchorRejectionCode,
    ArrivalEvaluation,
    Attraction,
    ConnectionEvaluation,
    Coordinate,
    DailyWeather,
    DateAssignment,
    DateRejection,
    DayTimeBounds,
    DayTimeBoundsResolution,
    EffectiveTimeWindow,
    ODBasis,
    RejectedAttraction,
    RejectionCode,
    SolverInputBatch,
    TimeRule,
    TimeWindowResolution,
    TravelTimeResult,
    TripTimeAnchors,
    WeatherAvailability,
    WeatherBasis,
    WeatherSeverity,
)
from .time_windows import evaluate_arrival, resolve_effective_window
from .transport import (
    ApproximateTravelTimeProvider,
    InMemoryTravelTimeProvider,
    TravelTimeProvider,
    evaluate_connection,
)
from .weather import assign_to_nearest_feasible_date, evaluate_weather_availability

__all__ = [
    "AnchorRejectionCode",
    "ArrivalEvaluation",
    "Attraction",
    "ApproximateTravelTimeProvider",
    "ConnectionEvaluation",
    "Coordinate",
    "DailyWeather",
    "DateAssignment",
    "DateRejection",
    "DayTimeBounds",
    "DayTimeBoundsResolution",
    "EffectiveTimeWindow",
    "InMemoryTravelTimeProvider",
    "ODBasis",
    "RejectedAttraction",
    "RejectionCode",
    "SolverInputBatch",
    "TimeRule",
    "TimeWindowResolution",
    "TravelTimeProvider",
    "TravelTimeResult",
    "TripTimeAnchors",
    "WeatherAvailability",
    "WeatherBasis",
    "WeatherSeverity",
    "assign_attraction_date",
    "assign_to_nearest_available_date",
    "assign_to_nearest_feasible_date",
    "evaluate_arrival",
    "evaluate_connection",
    "evaluate_weather_availability",
    "filter_solver_inputs",
    "is_open_on",
    "resolve_day_time_bounds",
    "resolve_effective_window",
]
