"""Deterministic itinerary solver primitives."""

from .anchors import resolve_day_time_bounds
from .availability import assign_attraction_date, assign_to_nearest_available_date, is_open_on
from .data_gate import filter_solver_inputs
from .day_assignment import assign_days, rebuild_day_plan
from .itinerary import route_itinerary
from .models import (
    AnchorRejectionCode,
    ArrivalEvaluation,
    Attraction,
    AttractionPreference,
    ConnectionEvaluation,
    ConstraintViolation,
    Coordinate,
    DailyWeather,
    DateAssignment,
    DateRejection,
    DayAllocation,
    DayPlan,
    DayTimeBounds,
    DayTimeBoundsResolution,
    EffectiveTimeWindow,
    ItineraryPlan,
    ItineraryReassignment,
    ItineraryUnplaced,
    MealPlacement,
    MealPlan,
    MealStatus,
    ODBasis,
    PaceLevel,
    RejectedAttraction,
    RejectionCode,
    RoutedDay,
    RouteSegment,
    RouteUnplaced,
    RouteValidation,
    RouteVisit,
    RoutingAttempt,
    SegmentedDay,
    SolverInputBatch,
    Step1Plan,
    TimeRule,
    TimeWindowResolution,
    TravelMode,
    TravelTimeResult,
    TripTimeAnchors,
    UnplacedAttraction,
    WeatherAvailability,
    WeatherBasis,
    WeatherSeverity,
)
from .quality import (
    ConstraintCount,
    ConstraintName,
    ItineraryAccounting,
    SolverQualityReport,
    constraint_name_for,
    evaluate_solver_quality,
)
from .routing import route_day, validate_routed_day
from .segments import route_segmented_day
from .time_windows import evaluate_arrival, resolve_effective_window
from .transport import (
    ApproximateTravelTimeProvider,
    InMemoryTravelTimeProvider,
    TravelTimeProvider,
    evaluate_connection,
)
from .weather import assign_to_nearest_feasible_date, evaluate_weather_availability

__all__ = [
    "AnchorRejectionCode",
    "ArrivalEvaluation",
    "Attraction",
    "AttractionPreference",
    "ApproximateTravelTimeProvider",
    "ConnectionEvaluation",
    "ConstraintCount",
    "ConstraintName",
    "ConstraintViolation",
    "Coordinate",
    "DailyWeather",
    "DateAssignment",
    "DateRejection",
    "DayAllocation",
    "DayPlan",
    "DayTimeBounds",
    "DayTimeBoundsResolution",
    "EffectiveTimeWindow",
    "InMemoryTravelTimeProvider",
    "ItineraryPlan",
    "ItineraryReassignment",
    "ItineraryUnplaced",
    "ItineraryAccounting",
    "MealPlacement",
    "MealPlan",
    "MealStatus",
    "ODBasis",
    "PaceLevel",
    "RejectedAttraction",
    "RejectionCode",
    "RoutedDay",
    "RouteSegment",
    "RouteUnplaced",
    "RouteValidation",
    "RouteVisit",
    "RoutingAttempt",
    "SegmentedDay",
    "SolverQualityReport",
    "SolverInputBatch",
    "Step1Plan",
    "TimeRule",
    "TimeWindowResolution",
    "TravelMode",
    "TravelTimeProvider",
    "TravelTimeResult",
    "TripTimeAnchors",
    "UnplacedAttraction",
    "WeatherAvailability",
    "WeatherBasis",
    "WeatherSeverity",
    "assign_attraction_date",
    "assign_days",
    "assign_to_nearest_available_date",
    "assign_to_nearest_feasible_date",
    "evaluate_arrival",
    "evaluate_connection",
    "evaluate_solver_quality",
    "evaluate_weather_availability",
    "filter_solver_inputs",
    "constraint_name_for",
    "is_open_on",
    "resolve_day_time_bounds",
    "resolve_effective_window",
    "rebuild_day_plan",
    "route_day",
    "route_itinerary",
    "route_segmented_day",
    "validate_routed_day",
]
