"""Versioned soft quality parameters (H3, ADR-0027)."""

QUALITY_ROUTE_BUDGET = 1024
QUALITY_MAX_PASSES = 6
QUALITY_DATE_PERMUTATION_LIMIT = 4
QUALITY_BALANCE_TOLERANCE_PER_MILLE = 200
QUALITY_NEIGHBOUR_SYMMETRIC_MIN = 10
QUALITY_NEIGHBOUR_DISTANCE_M = 1600
QUALITY_EVENING_REST_MIN = 15
QUALITY_REFINEMENT_DETERMINISTIC_LIMIT = 0.1
