"""Versioned soft quality parameters (H3, ADR-0027, ADR-0028)."""

QUALITY_ROUTE_BUDGET = 256
QUALITY_MAX_PASSES = 6
QUALITY_CANDIDATES_PER_ROUND = 40
QUALITY_WALL_TIME_LIMIT_SECONDS = 15.0
QUALITY_DATE_PERMUTATION_LIMIT = 4
QUALITY_BALANCE_TOLERANCE_PER_MILLE = 200
QUALITY_NEIGHBOUR_SYMMETRIC_MIN = 10
QUALITY_NEIGHBOUR_DISTANCE_M = 1600
QUALITY_NEIGHBOUR_SEVERE_EDGE_WEIGHT = 300
QUALITY_EVENING_REST_MIN = 15
QUALITY_REFINEMENT_DETERMINISTIC_LIMIT = 0.1
QUALITY_SCORE_TARGET_BPS = 9000
QUALITY_MIN_SCORE_IMPROVEMENT_BPS = 1
QUALITY_VISIT_SEVERE_RATIO_PER_MILLE = 800
QUALITY_FIXED_CONNECTION_SEVERE_MIN = 5
QUALITY_HALF_DAY_IDLE_MIN = 90
QUALITY_LUNCH_TARGET_MIN = 60
QUALITY_LUNCH_MIN_USABLE_MIN = 30
QUALITY_DINNER_TARGET_MIN = 90
QUALITY_DINNER_MIN_USABLE_MIN = 45
QUALITY_CONTINUOUS_ACTIVITY_RELAXED_MIN = 120
QUALITY_CONTINUOUS_ACTIVITY_BALANCED_MIN = 150
QUALITY_CONTINUOUS_ACTIVITY_TIGHT_MIN = 180
